### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [trivago/triava#1]
Hi,

The following source files are without license headers:

./src/main/java/com/trivago/triava/tcache/CacheWriteMode.java
./src/main/java/com/trivago/triava/tcache/action/ActionContext.java
./src/main/java/com/trivago/triava/tcache/action/GetAndPutAction.java
./src/main/java/com/trivago/triava/tcache/action/ReplaceAction.java
./src/main/java/com/trivago/triava/tcache/core/CacheWriterWrapper.java
./src/main/java/com/trivago/triava/tcache/core/NopCacheWriter.java
./src/main/java/com/trivago/triava/tcache/event/DispatchMode.java
./src/main/java/com/trivago/triava/tcache/event/ListenerCollection.java
./src/main/java/com/trivago/triava/tcache/event/TCacheEntryEvent.java
./src/main/java/com/trivago/triava/tcache/event/TCacheEntryEventCollection.java
./src/main/java/com/trivago/triava/tcache/util/ChangeStatus.java
./src/main/java/com/trivago/triava/tcache/util/KeyValueUtil.java
./src/main/java/com/trivago/triava/tcache/util/Serializing.java
./src/main/java/com/trivago/triava/tcache/util/TCacheConfigurationMBean.java
./src/main/java/com/trivago/triava/tcache/util/TCacheMBean.java

./src/test/java/com/trivago/triava/tcache/NamedAtomicInteger.java

Please, confirm the licensing of code and/or content/s, and add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by christian-esken** [comment]
Thanks for reporting.
Fixed: Added license headers in https://github.com/trivago/triava/commit/e7fb14a0ea5e0a17540f4781c6a244306747e3b8

**Comment by christian-esken** [comment]
Also added a license verification step, to be done before releases: https://github.com/trivago/triava/commit/f7bba76b91a74c41ea7904b727e108942fd3ec3a

**Comment by puntogil** [comment]
Again Thanks!
Regards
